version: '3'

services:

  app:
    image: openprocure-app-main-page
    build: .

  db:
    image: postgres:alpine
    environment:
    - POSTGRES_PASSWORD=123456

  auth:
    depends_on:
    - db
    image: budgetkey/auth
    env_file:
    - secret.env

  traefik:
    image: traefik
    command:
    - "--configFile=/etc-traefik/traefik.toml"
    ports:
    - "8001:443"
    volumes:
    - "./traefik.toml:/etc-traefik/traefik.toml"
    - "./traefik.crt:/etc-traefik/traefik.crt"
    - "./traefik.key:/etc-traefik/traefik.key"
