cards:
  supplier:
    - title: אף פעם לא עבדנו עם גורמים בממשלה
      cards:
        - 
          title: איך זה עובד בדיוק?
          icon: supp-a1
          text: |
            אנחנו אוספים ומחברים מידע ממקורות מידע ממשלתיים כך שתוכלו לקבל תשובות מהירות בנושאי רכש הממשלה ויחידותיה רוכשת וצורכת שירותים רבים. תהליך הרכש יכול להתבצע בצורת מכרז מרכזי (לכל יחידות הממשלה), מכרז משרדי או בצורה של פטור ממכרז במקרים שמוגדרים בחוק. לאחר אישור תהליך הרכש מתבצעות התקשרויות והעברות התשלום בין הגורם הרוכש לספק.
          action:
            text: על קראו עוד על תהליכי רכש	
            target: modal:methods_details
        -
          title: איך האתר הזה יכול לעזור לי	
          icon: supp-a2
          text: |
            אתר "רכש פתוח" אוסף ומאחד מידע ממקורות ממשלתיים שונים. תוכלו לצפות במידע כל מכרזים ורכישות עתידיות ולנתח העברות כספים שתועדו בעבר.
          action:
            text: ספרו לי עוד על מקורות המידע		
            target: modal:more_info
        -
          title: מאיפה מתחילם?	
          icon: supp-a3
          text: |
            חפשו נושא, שירות או מוצר אותו הייתם רוצים להציע לממשלה כדי לראות לצפות בהיסטוריית הרכש וההתקשרויות. ניתן גם להזין במסך החיפוש שמות של עסקים דומים כדי לצפות בהתקשרויות עבר והווה שלהם עם גופי ממשל ולאחר מכן להירשם לקבלת עדכונים שוטפים.	
          action:
            text: לחיפוש		
            target: href:/s/
    - title: אנחנו כבר מספקים סחורה / שירותים לממשלה
      cards:
        - 
          title: איך אוכל ללמוד עוד על התקשרות או פעולת רכש	
          icon: supp-b1
          text: |
            בכל אחד מהמסכים תממצאו טבלת שאילתות חכמה. תוכלו ללמוד בעזרתה על אופן העברת הכספים, סכומים, תאריך וגופים נוספם	  
          action:
            text: לדוגמה
            target: modal:explore_info
        - 
          title: איך אפשר להשאר מעודכנים?	
          icon: supp-b2
          text: |
            מערכת "רכש פתוח" מצליבה מידע מממספר מקורות. תוכלו לראות מה השתנה בשבוע או בחודש האחרון, ולקבל עדכונים שבועיים בנושאים שמעניינים אתכם.	
          action:
            text: למסך החיפושים השמורים	
            target: href:/p/
        - 
          title: מצאתי תהליך רכש מעניין, מה אפשר לעשות?	
          icon: supp-b3
          text: |
            בכל אחד מסוגי תהליכי הרכש ישנם שלבים שונים. נציג לך רעיונות לכיווני פעולה אפשריים במסכים השונים, אבל תמיד אפשר גם לקרוא עוד.	
          action:
            text: ספרו לי עוד	
            target: modal:methods_details
  gov:
    - title: פעם ראשונה ב״רכש פתוח״
      cards:
        - 
          title: איך זה עובד בדיוק?	
          icon: gov-a1
          text: |
            אנחנו אוספים ומחברים מידע ממקורות מידע ממשלתיים כך שתוכלו לקבל תשובות מהירות בנושאי רכש והתקשרויות	
          action:
            text: על מקורות המידע	
            target: modal:more_info
        - 
          title: מה אפשר לגלות כאן?	
          icon: gov-a2
          text: |
            תהליכי רכש בתהליך או מן העבר, התקשרויות קודמות של ספקים עם גופי ממשל	
          action:
            text: לחיפוש
            target: href:/s/
        - 
          title: איך אדע כשמשהו משתנה?	
          icon: gov-a3
          text: |
            באמצעות הרשמה למנגנון ההתראות תוכלו לקבל מייל מידי שבוע על עדכון הנוגעים לחיפושים השמורים שלכם	
          action:
            text: לחיפוש ושמירה	
            target: href:/s/
    - title: חזרתי, מה חדש?
      cards:
        - 
          title: איך למצוא ספקים פוטנציאלים?	
          icon: gov-b1
          text: |
            הזינו את שם המוצר, השירות או הספק שמעניין אתכם בחלון החיפוש.	
          action:
            text: לחיפוש
            target: href:/s/
        - 
          title: קרה משהו בתחומים שמעניינים אותי?	
          icon: gov-b2
          text: |
            התחברו ועברו למסך החיפושים השמורים שלכם. לחצו על כל אחד מהם כדי מה השתנה לאחרונה	
          action:
            text: למסך החיפושים השמורים	
            target: href:/p/
        - 
          title: איך ללמוד מניסיון קודם של אחרים בממשלה?	
          icon: gov-b3
          text: |
            סננו את תוצאות החיפוש לפי סוג פעולת הרכש - מכרז מרכזי, מכרז משרדי או פטור ממכרז וחפשו על פי מילות מפתח רלוונטיות. תוכלי להעמיק בבדיקה בעזרת טבלת השאילתות המתקדמות בעמודי המידע	
          action: 
            text: לחיפוש
            target: search
modals:
  more_info:
    title: עוד מידעעע
    text: |
      הנה משהו מעניין.
      הנה עוד משהו מעניין.
      